export const dummyData = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet',
        img: 'https://picsum.photos/200/300',
        shortDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod',
    },
    {
        id: 2,
        title: 'Lorem ipsum adipiscing elit',
        img: 'https://picsum.photos/200/300',
        shortDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod',
    },
    {
        id: 3,
        title: 'Lorem ipsum commodo consequat',
        img: 'https://picsum.photos/200/300',
        shortDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod nisi. Nunc euismod, nisi eget consectetur porta, nisl nisi consectetur nisi, euismod consectetur nisi nisi euismod',
    }
]